(ql:quickload :cl-ppcre)
(load "base.lisp")

(defclass AOJ (OJ)
     ())

(defmethod initialize-instance :after ((c AOJ) &rest initargs)
  (declare (ignore initargs))
  (setf (oj-url c) "http://judge.u-aizu.ac.jp/onlinejudge/")
  (setf (oj-url-problem-id c) "description.jsp?id=")
  (setf (oj-url-login c) nil)
  (setf (oj-url-submit c) "servlet/Submit")
  (setf (oj-lang-field c) '(("C" . "C") ("C++" . "C++") ("C++11" . "C++11")
                            ("JAVA" . "JAVA") ("C#" . "C#") ("D" . "D")))
  )

(defmethod sample-input ((c AOJ) html)
  (ppcre:register-groups-bind (nil in)
   ("<[hH][1-6]>Sample Input<\/[hH][1-6]>(.|\\r|\\n)+?<pre>[\\r\\n]+?((.|\\r|\\n)+?)[\\r\\n]+?<\/pre>" html)
   (format nil "~A~%" in)))

(defmethod sample-output ((c AOJ) html)
  (ppcre:register-groups-bind (nil out)
   ("<[hH][1-6]>Output for the Sample Input<\/[hH][1-6]>(.|\\r|\\n)+?<pre>[\\r\\n]+?((.|\\r|\\n)+?)[\\r\\n]+?<\/pre>" html)
   (format nil "~A~%" out)))

(defmethod submit-params ((c AOJ) source ext)
  `(("userID" . ,(oj-user c))
    ("password" . ,(oj-pass c))
    ("problemNO" . ,(format nil "~A" (oj-id c)))
    ("language" . ,(cdr (assoc
                         (cdr (assoc ext (oj-ext-lang-map c) :test 'string=))
                         (oj-lang-field c)
                         :test 'string=)))
    ("sourceCode" . ,source)
    ("submit" . "Send")))
