(ql:quickload :cl-ppcre)
(load "base.lisp")

(defclass POJ (OJ)
     ())

(defmethod initialize-instance :after ((c POJ) &rest initargs)
  (declare (ignore initargs))
  (setf (oj-url c) "http://poj.org/")
  (setf (oj-url-problem-id c) "problem?id=")
  (setf (oj-url-login c) "login")
  (setf (oj-url-submit c) "submit")
  (setf (oj-login-params c) `(("user_id1" . ,(oj-user c))
                              ("password1" . ,(oj-pass c))))
  (setf (oj-lang-field c) '(("G++" . "0") ("GCC" . "1") ("Java" . "2") ("Pascal" . "3")
                            ("C++" . "4") ("C" . "5") ("Fortran" . "6")))
  )

(defmethod sample-input ((c POJ) html)
  (ppcre:register-groups-bind (in)
   ("<pre class=\"sio\">((.|\\r|\\n)+?)<\/pre>" html)
   (format nil "~A~%" in)))

(defmethod sample-output ((c POJ) html)
  (ppcre:register-groups-bind (nil nil nil out)
   ("<pre class=\"sio\">((.|\\r|\\n)+?)<\/pre>(.|\\r|\\n)+?<pre class=\"sio\">((.|\\r|\\n)+?)<\/pre>" html)
   (format nil "~A~%" out)))

(defmethod submit-params ((c POJ) source ext)
  `(("language" . ,(cdr (assoc
                         (cdr (assoc ext (oj-ext-lang-map c) :test 'string=))
                         (oj-lang-field c)
                         :test 'string=)))
    ("problem_id" . ,(format nil "~A" (oj-id c)))
    ("source" . ,source)
    ("submit" . "Submit")))
